buffer_size: 10_000
buffer_device: cpu
batch_size: 4096
gamma: 0.95

eps_init: 1.0
eps_end: 0.05

n_optim: 8

actor:
  cnn_kwargs:
    num_cells: [32, 64, 128, 4]
    kernel_sizes: [3, 3, 3, 1]
    strides: [1, 1, 1, 1]
    paddings: [1, 1, 1, 0]
    activation_class: ReLU

  mlp_kwargs:
    depth: 2
    num_cells: [64, 64]
    activation_class: ReLU
