seed: 0
num_envs: 2048
board_size: 15
device: cuda
buffer_device: cpu # If transitions are stored on GPU, at the moment the memory cannot be properly released.
buffer_batch_size: 512
run_dir:

augment: false
n_augment: 8

epochs: 500
rounds: 120
save_interval: -1
log_interval: 5

# psro
meta_solver: nash
mean_threshold: 0.99
std_threshold: 0.005
min_iter_steps: 25
max_iter_steps: 300

# checkpoint: pretrained_models/${board_size}_${board_size}/0.pt

wandb:
  group: ${board_size}_${board_size}_sp
  project: gomoku_rl
  mode: online # set to 'disabled' when debugging locally

defaults:
  - _self_
  - algo: ppo
