seed: 0
num_envs: 1024
board_size: 15
device: cuda
buffer_device: cpu
buffer_batch_size: 512
run_dir:

augment: true

epochs: 800
rounds: 80
save_interval: 100
log_interval: 5

# psro
mean_threshold: 0.99
std_threshold: 0.005

black_checkpoint: pretrained_models/${board_size}_${board_size}/baseline.pt
white_checkpoint: pretrained_models/${board_size}_${board_size}/baseline.pt

wandb:
  group: ${board_size}_${board_size}
  project: gomoku_rl
  mode: online # set to 'disabled' when debugging locally

defaults:
  - _self_
  - algo: ppo
