seed: 0
num_envs: 512
board_size: 15
device: cuda
out_device: cpu
run_dir:

augment: false

epochs: 200
steps: 225
save_interval: -1
log_interval: 5


# checkpoint: pretrained_models/${board_size}_${board_size}/${algo.name}/0.pt

wandb:
  group: ${board_size}_${board_size}_${algo.name}_InRL_sp
  project: gomoku_rl
  mode: online # set to 'disabled' when debugging locally

defaults:
  - _self_
  - algo: ppo
