seed: 0
num_envs: 2048
board_size: 8
device: cuda

epochs: 100
episode_len: 64

wandb:
  group: board_${board_size}_${board_size}
  project: gomoku_rl
  mode: online # set to 'disabled' when debugging locally

defaults:
  - algo: ppo
