seed: 0
num_envs: 1024
board_size: 15
device: cuda
out_device: cpu
run_dir:

augment: false

epochs: 1000
rounds: 64 
save_interval: -1

# psro
meta_solver: uniform
mean_threshold: 0.99
std_threshold: 0.005
min_iter_steps: 30
max_iter_steps: 500

checkpoint: pretrained_models/${board_size}_${board_size}/${algo.name}/0.pt

population_dir: pretrained_models/${board_size}_${board_size}/${algo.name}

wandb:
  group: ${board_size}_${board_size}_${algo.name}_sp
  project: gomoku_rl
  mode: online # set to 'disabled' when debugging locally

defaults:
  - algo: ppo
  - baseline: ppo
  - _self_
