seed: 0
num_envs: 1024
board_size: 15
device: cuda
run_dir: 

augment: true # to do

epochs: 100
rounds: 50
log_interval: 5
save_interval: -1

checkpoint: pretrained_models/${board_size}_${board_size}/baseline.pt
color: white

opponent_checkpoint: pretrained_models/${board_size}_${board_size}/baseline.pt

wandb:
  group: fixed_opponent_${board_size}_${board_size}
  project: gomoku_rl
  mode: online # set to 'disabled' when debugging locally

defaults:
  - _self_
  - algo: ppo
