seed: 0
num_envs: 1024
board_size: 15
device: cuda
run_dir: 

augment: true

epochs: 60
steps: 128
save_interval: 10
log_interval: 5

checkpoint: pretrained_models/${board_size}_${board_size}/baseline.pt

wandb:
  group: self_play_${board_size}_${board_size}
  project: gomoku_rl
  name: test
  mode: online # set to 'disabled' when debugging locally

defaults:
  - _self_
  - algo: ppo
