seed: 0
num_envs: 512
board_size: 15
device: cuda
out_device: cpu
run_dir:

augment: false

epochs: 500
rounds: 113 # This is a design flaw, if rounds*2<board_size^2, later states can never be explored
save_interval: -1
log_interval: 5

# psro
meta_solver: nash
mean_threshold: 0.99
std_threshold: 0.005
min_iter_steps: 30
max_iter_steps: 300

# checkpoint: pretrained_models/${board_size}_${board_size}/${algo.name}/0.pt

# population_dir: pretrained_models/${board_size}_${board_size}/${algo.name}

wandb:
  group: ${board_size}_${board_size}_${algo.name}_sp
  project: gomoku_rl
  mode: online # set to 'disabled' when debugging locally

defaults:
  - _self_
  - algo: ppo
