seed: 0
num_envs: 256
board_size: 10
device: cuda
run_dir:

augment: false

epochs: 1000
rounds: 50
save_interval: -1
log_interval: 5

# psro
meta_solver: nash
mean_threshold: 0.99
std_threshold: 0.005
min_iter_steps: 40
max_iter_steps: 300

# black_checkpoint: pretrained_models/${board_size}_${board_size}/0.pt
# white_checkpoint: pretrained_models/${board_size}_${board_size}/0.pt

wandb:
  group: ${board_size}_${board_size}
  project: gomoku_rl
  mode: online # set to 'disabled' when debugging locally

defaults:
  - _self_
  - algo: ppo
