seed: 0
num_envs: 2048
board_size: 15
device: cuda
buffer_device: cpu # If transitions are stored on GPU, at the moment the memory cannot be properly released.
buffer_batch_size: 512
run_dir: 

augment: false

epochs: 100
rounds: 120
log_interval: 5
save_interval: -1

checkpoint: pretrained_models/${board_size}_${board_size}/baseline.pt
color: white

opponent_checkpoint: pretrained_models/${board_size}_${board_size}/baseline.pt

wandb:
  group: fixed_opponent_${board_size}_${board_size}
  project: gomoku_rl
  mode: online # set to 'disabled' when debugging locally

defaults:
  - _self_
  - algo: ppo
