seed: 0
num_envs: 1024
board_size: 15
device: cuda
out_device: cpu
run_dir:

augment: false

epochs: 100
steps: 128
save_interval: -1


# checkpoint: pretrained_models/${board_size}_${board_size}/${algo.name}/0.pt

wandb:
  group: ${board_size}_${board_size}_${algo.name}_InRL_sp
  project: gomoku_rl
  mode: online # set to 'disabled' when debugging locally

defaults:
  - _self_
  - algo: ppo
  - baseline: ppo_no_share
