seed: 0
num_envs: 256
board_size: 15
device: cuda
run_dir:

augment: false
n_augment: 8

epochs: 500
rounds: 113 # This is a design flaw, if rounds*2<board_size^2, later states can never be explored
save_interval: -1
log_interval: 5

# psro
meta_solver: nash
mean_threshold: 0.99
std_threshold: 0.005
min_iter_steps: 20
max_iter_steps: 300

# checkpoint: pretrained_models/${board_size}_${board_size}/0.pt

wandb:
  group: ${board_size}_${board_size}_sp
  project: gomoku_rl
  mode: online # set to 'disabled' when debugging locally

defaults:
  - _self_
  - algo: ppo
