seed: 0
num_envs: 1024
board_size: 15
device: cuda
out_device: cpu
run_dir:

augment: false

epochs: 500
rounds: 64 
save_interval: -1

# psro
meta_solver: last_3
mean_threshold: 0.99
std_threshold: 0.005
min_iter_steps: 30
max_iter_steps: 300

# checkpoint: pretrained_models/${board_size}_${board_size}/${algo.name}/1.pt

# population_dir: pretrained_models/${board_size}_${board_size}/${algo.name}

# algo:
#   share_network: false

wandb:
  group: ${board_size}_${board_size}_${algo.name}_sp
  project: gomoku_rl
  mode: online # set to 'disabled' when debugging locally

defaults:
  - algo: ppo
  - baseline: ppo_no_share
  - _self_
