seed: 0

num_envs: 512
board_size: 15
device: cuda
storing_device: cpu

total_frames: 50_000_000
update_interval: 20
update_threshold: 0.9

initial_policy: 

root_dir: sp_root

wandb:
  group: board_${board_size}_${board_size}
  project: gomoku_rl
#  mode: online # set to 'disabled' when debugging locally

defaults:
  - algo: ppo
