seed: 0
num_envs: 1024
board_size: 15
device: cuda

augment: true # to do

epochs: 100
rounds: 64

black_checkpoint: pretrained_models/${board_size}_${board_size}/baseline.pt
white_checkpoint: pretrained_models/${board_size}_${board_size}/baseline.pt

wandb:
  group: InRL_${board_size}_${board_size}
  project: gomoku_rl
  mode: online # set to 'disabled' when debugging locally

defaults:
  - _self_
  - algo: ppo
