seed: 0
num_envs: 1024
board_size: 15
device: cuda
out_device: cpu
run_dir:

augment: false

epochs: 1000
steps: 128
save_interval: 250

# psro
meta_solver: uniform
mean_threshold: 0.99
std_threshold: 0.005
min_iter_steps: 20
max_iter_steps: 300

black_checkpoint: pretrained_models/${board_size}_${board_size}/${algo.name}/0.pt
white_checkpoint: pretrained_models/${board_size}_${board_size}/${algo.name}/1.pt

wandb:
  group: ${board_size}_${board_size}
  project: gomoku_rl
  mode: online # set to 'disabled' when debugging locally

defaults:
  - _self_
  - algo: ppo
  - baseline: ppo
