num_envs: 256
board_size: 6
device: cuda

total_frames: 50_000_000
frames_per_batch: ${eval:64*${num_envs}}

initial_opponent_ckpt: player1.pt

wandb:
  group: debug
  project: gomoku_rl
  mode: online # set to 'disabled' when debugging locally

defaults:
  - algo: dqn
