seed: 0

num_envs: 256
board_size: 6
device: cuda

total_frames: 50_000_000
frames_per_batch: ${eval:64*${num_envs}}

initial_opponent_ckpt: player0.pt

wandb:
  group: board_${board_size}_${board_size}
  project: gomoku_rl
  mode: online # set to 'disabled' when debugging locally

defaults:
  - algo: ppo
