name: ppo

# ppo
ppo_epochs: 3
clip_param: 0.2 # 0.2
entropy_coef: 0.01 # 0.01
gae_lambda: 0.95
gamma: 0.99 # 0.99
max_grad_norm: 0.5
batch_size: 4096

normalize_advantage: true
average_gae: False

share_network: true

optimizer:
  name: adam
  kwargs:
    lr: 1e-4


num_channels: 64
num_residual_blocks: 4


