name: ppo


# ppo
train_every: 64
num_minibatches: 16
ppo_epochs: 4
clip_param: 0.1 # 0.2 可能需要搜索
entropy_coef: 0.005 # 0.01
gae_lambda: 0.95
gamma: 0.99 # 0.99
max_grad_norm: 1.0


lr: 5e-4

actor:
  cnn_kwargs:
    num_cells: [32, 64, 128, 4]
    kernel_sizes: [3, 3, 3, 1]
    strides: [1, 1, 1, 1]
    paddings: [1, 1, 1, 0]
    activation_class: ReLU

  mlp_kwargs:
    depth: 2
    num_cells: [64, 64]
    activation_class: ReLU


critic:
  cnn_kwargs:
    num_cells: [32, 64, 128, 4]
    kernel_sizes: [3, 3, 3, 1]
    strides: [1, 1, 1, 1]
    paddings: [1, 1, 1, 0]
    activation_class: ReLU

  mlp_kwargs:
    depth: 2
    num_cells: [64, 64]
    activation_class: ReLU